# Company's sales Data of 10 years

In [1]:
import numpy as np

In [4]:
data=np.loadtxt("random_unsorted_sales_data.csv",dtype=str,delimiter=',')
print(data)
print("\n\n")
actualData=np.array(data[1:,1:],dtype=int)
print(actualData)

[['Month' '2016' '2017' '2018' '2019' '2020' '2021' '2022' '2023' '2024'
  '2025']
 ['Jan' '182' '428' '350' '186' '151' '268' '100' '182' '201' '294']
 ['Feb' '410' '167' '452' '179' '439' '231' '210' '229' '388' '337']
 ['Mar' '423' '493' '373' '465' '271' '356' '240' '393' '101' '332']
 ['Apr' '315' '424' '128' '138' '249' '267' '350' '269' '254' '130']
 ['May' '443' '134' '323' '399' '210' '386' '214' '100' '408' '246']
 ['Jun' '353' '467' '168' '395' '93' '321' '344' '425' '132' '465']
 ['Jul' '419' '171' '446' '343' '114' '285' '160' '499' '129' '439']
 ['Aug' '467' '81' '469' '133' '185' '339' '389' '270' '481' '297']
 ['Sep' '123' '241' '281' '349' '430' '383' '350' '294' '331' '269']
 ['Oct' '375' '292' '287' '316' '417' '446' '132' '359' '489' '296']
 ['Nov' '331' '267' '459' '120' '236' '94' '380' '144' '424' '406']
 ['Dec' '88' '423' '208' '215' '142' '218' '160' '471' '242' '498']]



[[182 428 350 186 151 268 100 182 201 294]
 [410 167 452 179 439 231 210 229 388 337]
 [4

### Slicing

In [3]:
# data of last 5 years
print(data[:,6:])

# data of 2022
print(data[:,7])

[['2021' '2022' '2023' '2024' '2025']
 ['268' '100' '182' '201' '294']
 ['231' '210' '229' '388' '337']
 ['356' '240' '393' '101' '332']
 ['267' '350' '269' '254' '130']
 ['386' '214' '100' '408' '246']
 ['321' '344' '425' '132' '465']
 ['285' '160' '499' '129' '439']
 ['339' '389' '270' '481' '297']
 ['383' '350' '294' '331' '269']
 ['446' '132' '359' '489' '296']
 ['94' '380' '144' '424' '406']
 ['218' '160' '471' '242' '498']]
['2022' '100' '210' '240' '350' '214' '344' '160' '389' '350' '132' '380'
 '160']


### Operation: Sales Analysis


In [64]:
# Total Sales each year

print("total sales each year:\n",np.sum(actualData,axis=0))


# average sales each year
print("\naverage sales each year:\n",np.mean(actualData,axis=0))


# maximum sale from each year
print("\nmaximum sale of each year \n",np.max(actualData,axis=0))


# minimum sale from each year
print("\nminimum sale of each year \n",np.min(actualData,axis=0))


bestMonths=list(str(data[i+1][0]) for i in np.argmax(actualData,axis=0))
print("\nbest month sales of each year:\n",bestMonths)


worstMonths=list(str(data[i+1][0]) for i in np.argmin(actualData,axis=0))
print("\nworst month sales of each year:\n",worstMonths)

total sales each year:
 [3929 3588 3944 3238 2937 3594 3029 3635 3580 4009]

average sales each year:
 [327.41666667 299.         328.66666667 269.83333333 244.75
 299.5        252.41666667 302.91666667 298.33333333 334.08333333]

maximum sale of each year 
 [467 493 469 465 439 446 389 499 489 498]

minimum sale of each year 
 [ 88  81 128 120  93  94 100 100 101 130]

best month sales of each year:
 ['Aug', 'Mar', 'Aug', 'Mar', 'Feb', 'Oct', 'Aug', 'Jul', 'Oct', 'Dec']

worst month sales of each year:
 ['Dec', 'Aug', 'Apr', 'Nov', 'Jun', 'Nov', 'Jan', 'May', 'Mar', 'Apr']
