# Project 2- Airport Cabs Data Analysis

In [1]:
import numpy as np

In [16]:
data=np.genfromtxt('nyc_taxis.csv',delimiter=',',skip_header=True)  # data would be in float type
print(data)

[[2.016e+03 1.000e+00 1.000e+00 ... 1.165e+01 6.999e+01 1.000e+00]
 [2.016e+03 1.000e+00 1.000e+00 ... 8.000e+00 5.430e+01 1.000e+00]
 [2.016e+03 1.000e+00 1.000e+00 ... 0.000e+00 3.780e+01 2.000e+00]
 ...
 [2.016e+03 6.000e+00 3.000e+01 ... 5.000e+00 6.334e+01 1.000e+00]
 [2.016e+03 6.000e+00 3.000e+01 ... 8.950e+00 4.475e+01 1.000e+00]
 [2.016e+03 6.000e+00 3.000e+01 ... 0.000e+00 5.484e+01 2.000e+00]]


### Mean speed of all the cab rides

In [27]:
# trip length is time
timeInHours=data[:,8]/3600   # seconds to hours
# print(timeInHours)

distance=data[:,7]
# print(distance)

# speed=distance/time(hours)
speed=distance/timeInHours
# print(speed)   # km/h

speedMean=np.mean(speed)
print("\nmean of speed is:\n",speedMean)



mean of speed is:
 32.24258580925573


### Calculate the number of rides taken in any specific month

In [ ]:
# pickup_month is from 1..12, denoting jan .. dec respectively

# 2nd col is month column
ridesInFebruary=data[data[:,1]==2]
print(ridesInFebruary.shape)   # gives (rows,col)
print("\nNumber of rides taken in the month of February:\n",ridesInFebruary.shape[0])

(13333, 15)

Number of rides taken in the month of February:
 13333


### Calculate the number of rides with a tip greater than $50

In [48]:
# 12th col is tim_Amount column, -3 if count from last
tipAmounts=data[data[:,-3]>50,-3]  # data[condition]=> select all column. 2nd argument for 12th column

print("\nNumber of rides with a tip greater than 50$ are:\n",tipAmounts.shape[0])


Number of rides with a tip greater than 50$ are:
 16


### Calculate the number of rides where drop was JFK airport

In [52]:
# drop of location code for JFK is assume 2
dropOffAtJFK=data[data[:,6]==2,6]
print("\nNumber of rides where dropOff was JFK airport are:\n",dropOffAtJFK.shape[0])


Number of rides where dropOff was JFK airport are:
 11832
